export const DISC_DATA = [
  {
    id: 1,
    name: 'Avenger SS',
    type: 'Driver',
    stability: 'Overstable',
    speed: 10,
    glide: 5,
    turn: -1,
    fade: 2,
    color: '#ff6b35',
    weight: 175,
    plastic: 'Z',
  },
  {
    id: 2,
    name: 'Raptor',
    type: 'Midrange',
    stability: 'Overstable',
    speed: 5,
    glide: 4,
    turn: -1,
    fade: 2,
    color: '#004e89',
    weight: 180,
    plastic: 'Z',
  },
  {
    id: 3,
    name: 'Luna',
    type: 'Putter',
    stability: 'Stable',
    speed: 2,
    glide: 4,
    turn: 0,
    fade: 1,
    color: '#f77f00',
    weight: 175,
    plastic: 'Luna',
  },
  {
    id: 4,
    name: 'Predator',
    type: 'Driver',
    stability: 'Overstable',
    speed: 9,
    glide: 3,
    turn: 0,
    fade: 3,
    color: '#2a2d34',
    weight: 170,
    plastic: 'Z',
  },
  {
    id: 5,
    name: 'Mantis',
    type: 'Midrange',
    stability: 'Understable',
    speed: 5,
    glide: 5,
    turn: -2,
    fade: 1,
    color: '#06d6a0',
    weight: 178,
    plastic: 'Big Z',
  },
  {
    id: 6,
    name: 'Buzzz',
    type: 'Midrange',
    stability: 'Stable',
    speed: 5,
    glide: 4,
    turn: -1,
    fade: 1,
    color: '#118ab2',
    weight: 177,
    plastic: 'Champion',
  },
  {
    id: 7,
    name: 'Titan',
    type: 'Driver',
    stability: 'Understable',
    speed: 9,
    glide: 4,
    turn: -3,
    fade: 1,
    color: '#ef476f',
    weight: 165,
    plastic: 'Z Lite',
  },
  {
    id: 8,
    name: 'Magnet',
    type: 'Putter',
    stability: 'Stable',
    speed: 2,
    glide: 3,
    turn: 0,
    fade: 1,
    color: '#ffd60a',
    weight: 173,
    plastic: 'Super Straight',
  },
  {
    id: 9,
    name: 'Undertaker',
    type: 'Midrange',
    stability: 'Stable',
    speed: 5,
    glide: 5,
    turn: -1,
    fade: 1,
    color: '#2e1a47',
    weight: 175,
    plastic: 'ESP',
  },
  {
    id: 10,
    name: 'Nuke',
    type: 'Driver',
    stability: 'Overstable',
    speed: 13,
    glide: 3,
    turn: -2,
    fade: 4,
    color: '#a23b72',
    weight: 175,
    plastic: 'Z',
  },
  {
    id: 11,
    name: 'Pig',
    type: 'Midrange',
    stability: 'Overstable',
    speed: 4,
    glide: 3,
    turn: 0,
    fade: 2,
    color: '#f4d35e',
    weight: 179,
    plastic: 'Luna',
  },
  {
    id: 12,
    name: 'Avenger',
    type: 'Driver',
    stability: 'Stable',
    speed: 10,
    glide: 5,
    turn: -1,
    fade: 1,
    color: '#ee964b',
    weight: 172,
    plastic: 'Big Z',
  },
  {
    id: 13,
    name: 'Anax',
    type: 'Driver',
    stability: 'Stable',
    speed: 10,
    glide: 6,
    turn: -1,
    fade: 1,
    color: '#023047',
    weight: 170,
    plastic: 'Z',
  },
  {
    id: 14,
    name: 'Comet',
    type: 'Midrange',
    stability: 'Stable',
    speed: 5,
    glide: 5,
    turn: -2,
    fade: 1,
    color: '#8ecae6',
    weight: 176,
    plastic: 'R-Pro',
  },
]
